### ISSUE TITLE
Access-Control-Allow-Private-Network header

### ISSUE THREAD

**Issue by atompkins** [lwsjs/cors#1]
Would it be possible to add Access-Control-Allow-Private-Network: true header for preflight checks?

**Comment by atompkins** [comment]
I looked at the code after posting this, my bad. The answer is no.

**Comment by 75lb** [comment]
This plugin wraps `@koa/cors` which doesn't support `Access-Control-Allow-Private-Network` yet.. But I [have asked](https://github.com/koajs/cors/issues/81).. 

However, it is still very much possible to support this header using [custom middleware](https://github.com/koajs/cors/issues/81) - would that work for you?

**Comment by atompkins** [comment]
Yes thank you :)
I had come to that conclusion myself. I'd never looked at it before but it seems fairly straightforward.

**Comment by 75lb** [comment]
I just wrote another [quick middleware example](https://github.com/lwsjs/local-web-server/wiki/Middleware-example:-a-custom-response-for-login-requests) to help explain how they're used.. 

Let me know if you come up with a useful plugin to solve this issue for future users

**Comment by 75lb** [comment]
I'm still waiting for a response from Koa regarding adding support for this header - re-opening the ticket and will add support myself if I'm waiting much longer.. 

@atompkins What is your particular use case for this header? In what scenario does this header fix your issue?

**Comment by atompkins** [comment]
I develop a Greasemonkey script. The same issue would occur for an API though.
This is only a problem in development and only in Chrome, I haven't tried other Chromium based browsers.

I wrote a very primitive middleware for my project
https://github.com/atompkins/fallenswordhelper/blob/6a2495564804aaf51707dd240d934906a4f60141/scripts/mw-private-network.js
It has to go in the stack before cors.

**Comment by 75lb** [comment]
Your middleware looks fine to me - gets the job done.. Support for this header has [just landed in koa/cors](https://github.com/koajs/cors/pull/83), could you take a quick look at the patch and confirm whether or not the added behaviour solves your issue?

**Comment by atompkins** [comment]
looks like it should work

**Comment by atompkins** [comment]
is it possible to update the @kao/cors dependency to a newer version?

**Comment by 75lb** [comment]
working on it, watch this space..

**Comment by 75lb** [comment]
Released in [local-web-server v5.3.0](https://github.com/lwsjs/local-web-server/releases/tag/v5.3.0). Let me know if there's anything else..
